# kubectl apply -f paul-huayhua-19-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: paul-huayhua-19-secret
  namespace: paul-huayhua-19-namespace
type: Opaque
data:
  MONGODB_URI: <BASE64_MONGODB_URI>
  GROQ_API_KEY: <BASE64_GROQ_API_KEY>
  GROQ_MODEL: <BASE64_GROQ_MODEL>
  RAPIDAPI_KEY: <BASE64_RAPIDAPI_KEY>
  RAPIDAPI_HOST_WEATHER: <BASE64_RAPIDAPI_HOST_WEATHER>

# Para generar los valores en base64:
# echo -n "tu_valor" | base64
# echo "valor_base64" | base64 --decode
