# kubectl apply -f paul-huayhua-19-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: paul-huayhua-19-secret
  namespace: paul-huayhua-19-namespace
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9wYXVsaHVheWh1YWphcXVlaHVhX2RiX3VzZXI6NkVWeVg4b0pjd2t3MEtZVEBjbHVzdGVyMC5haTJwN2tzLm1vbmdvZGIubmV0LzE5X3BhdWxfaHVheWh1YT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  GROQ_API_KEY: Z3NrX0VLM3ZlNWJXSktvT01kTjFRYldHV0dkeWIzRll6aXZzRlgwTEYxZHVQQXo3RnBjS2poMUc=
  GROQ_MODEL: bWV0YS1sbGFtYS9sbGFtYS00LXNjb3V0LTE3Yi0xNmUtaW5zdHJ1Y3Q=
  RAPIDAPI_KEY: YWFhZjAxYjE0OW1zaDJkMTI5YzIxZjZjOTYwZHAxYjQ5M2Vqc24xMDc5NmQwY2M4ZDE=
  RAPIDAPI_HOST_WEATHER: d2VhdGhlci1pbnRlbGxpZ2VuY2UxLnAucmFwaWRhcGkuY29t

# https://base64.guru/converter
# echo -n "tu_valor" | base64
# echo "valor_base64" | base64 --decode